name: "@name@"
version: "@version@"
main: "@entry_point@"
bootstrapper: "dev.remodded.recore.paper.ReCoreBootstrapper"
description: "@description@"
load: STARTUP
author: "@author@"
api-version: "1.20"
loadbefore: [ ]
softdepend: [ ]
